@baseUrl = http://localhost:5078

### # @name Create Customer
< {%
client.global.set("customerFirstName", "John");
client.global.set("customerLastName", "Smith");
client.global.set("customerDateOfBirth", "1985-06-15");
%}

POST {{baseUrl}}/api/customers
Content-Type: application/json

{
  "FirstName": "{{customerFirstName}}",
  "LastName": "{{customerLastName}}",
  "DateOfBirth": "{{customerDateOfBirth}}"
}

> {%
client.global.set("customerId", response.body.CustomerId);
%}

###

### # @name Create Address
< {%
client.global.set("addressLine1", "123 Main Street");
client.global.set("addressLine2", "Apt 4B");
client.global.set("addressLine3", "Flat 2");
client.global.set("postcode", "SW1A1AA");
%}

POST {{baseUrl}}/api/addresses
Content-Type: application/json

{
  "AddressLine1": "{{addressLine1}}",
  "AddressLine2": "{{addressLine2}}",
  "AddressLine3": "{{addressLine3}}",
  "Postcode": "{{postcode}}"
}

> {%
client.global.set("addressId", response.body.AddressId);
%}

###

### # @name Sell Household Policy
< {%
client.global.set("policyStartDate", "2026-09-05");
client.global.set("policyEndDate", "2027-09-05");
client.global.set("policyAmount", 500.00);
client.global.set("autoRenew", true);
client.global.set("paymentReference", "PAY-001");
client.global.set("paymentType", "DirectDebit");
client.global.set("paymentAmount", 500.00);
%}

POST {{baseUrl}}/api/policies/households
Content-Type: application/json

{
  "StartDate": "{{policyStartDate}}",
  "EndDate": "{{policyEndDate}}",
  "Amount": {{policyAmount}},
  "AutoRenew": {{autoRenew}},
  "CustomerIds": ["{{customerId}}"],
  "AddressId": "{{addressId}}",
  "Payment": {
    "PaymentReference": "{{paymentReference}}",
    "Type": "{{paymentType}}",
    "Amount": {{paymentAmount}}
  }
}

> {%
client.global.set("policyReference", response.body.UniqueReference);
%}

###

### # @name Retrieve Policy
GET {{baseUrl}}/api/policies/{{policyReference}}


###

### # @name Retrieve Policy Payments
GET {{baseUrl}}/api/policies/{{policyReference}}/payments


###

### # @name Retrieve Policy Refunds
GET {{baseUrl}}/api/policies/{{policyReference}}/refunds


###

### # @name Retrieve Customer
GET {{baseUrl}}/api/customers/{{customerId}}


###

### # @name Retrieve Customer Policies
GET {{baseUrl}}/api/customers/{{customerId}}/policies

