@baseUrl = http://localhost:5078

### # @name Create Customer
< {%
client.global.set("customerFirstName", "Jane");
client.global.set("customerLastName", "Doe");
client.global.set("customerDateOfBirth", "1980-03-22");
%}

POST {{baseUrl}}/api/customers
Content-Type: application/json

{
  "FirstName": "{{customerFirstName}}",
  "LastName": "{{customerLastName}}",
  "DateOfBirth": "{{customerDateOfBirth}}"
}

> {%
client.global.set("customerId", response.body.CustomerId);
%}

###

### # @name Create Address
< {%
client.global.set("addressLine1", "456 Oak Avenue");
client.global.set("addressLine2", "Unit 3");
client.global.set("addressLine3", "");
client.global.set("postcode", "M1 1AA");
%}

POST {{baseUrl}}/api/addresses
Content-Type: application/json

{
  "AddressLine1": "{{addressLine1}}",
  "AddressLine2": "{{addressLine2}}",
  "AddressLine3": "{{addressLine3}}",
  "Postcode": "{{postcode}}"
}

> {%
client.global.set("addressId", response.body.AddressId);
%}

###

### # @name Sell Buy-to-Let Policy
< {%
client.global.set("policyStartDate", "2026-09-05");
client.global.set("policyEndDate", "2027-09-05");
client.global.set("policyAmount", 750.00);
client.global.set("autoRenew", true);
client.global.set("paymentReference", "PAY-002");
client.global.set("paymentType", "DirectDebit");
client.global.set("paymentAmount", 750.00);
%}

POST {{baseUrl}}/api/policies/buytolet
Content-Type: application/json

{
  "StartDate": "{{policyStartDate}}",
  "EndDate": "{{policyEndDate}}",
  "Amount": {{policyAmount}},
  "AutoRenew": {{autoRenew}},
  "CustomerIds": ["{{customerId}}"],
  "AddressId": "{{addressId}}",
  "Payment": {
    "PaymentReference": "{{paymentReference}}",
    "Type": "{{paymentType}}",
    "Amount": {{paymentAmount}}
  }
}

> {%
client.global.set("policyReference", response.body.UniqueReference);
%}

###

### # @name Calculate Cancellation Quote
< {%
client.global.set("cancellationDate", "2026-09-20");
%}

POST {{baseUrl}}/api/policies/{{policyReference}}/cancellation-quotes
Content-Type: application/json

{
  "CancellationDate": "{{cancellationDate}}"
}


###

### # @name Cancel Policy
PUT {{baseUrl}}/api/policies/{{policyReference}}/cancellation
Content-Type: application/json

{
  "CancellationDate": "{{cancellationDate}}"
}


###

### # @name Retrieve Cancelled Policy
GET {{baseUrl}}/api/policies/{{policyReference}}

