@baseUrl = http://localhost:5078

### # @name Retrieve Policy Before Renewal
GET {{baseUrl}}/api/policies/POL-RENEW-DEMO


###

### # @name Renew Policy
< {%
client.global.set("renewalStartDate", "2027-09-05");
client.global.set("renewalEndDate", "2028-09-05");
client.global.set("renewalAmount", 550.00);
%}

POST {{baseUrl}}/api/policies/POL-RENEW-DEMO/renewals
Content-Type: application/json

{
  "StartDate": "{{renewalStartDate}}",
  "EndDate": "{{renewalEndDate}}",
  "Amount": {{renewalAmount}}
}

> {%
client.global.set("renewedPolicyReference", response.body.UniqueReference);
%}

###

### # @name Retrieve Renewed Policy
GET {{baseUrl}}/api/policies/{{renewedPolicyReference}}

