@baseUrl = http://localhost:5078
# Note: Run sell-household-policy.http or sell-buytolet-policy.http first to set policyReference

### Retrieve a Policy
GET {{baseUrl}}/api/policies/{{policyReference}}

###

### Retrieve Payments for a Policy
GET {{baseUrl}}/api/policies/{{policyReference}}/payments

###

### Retrieve Refunds for a Policy
GET {{baseUrl}}/api/policies/{{policyReference}}/refunds
